
def infomacoes_uso():

    print(f"╔═══════════════════════════════════════════════════════════════════════════════════════════════════════╗\n")
    print(f"                   ABA DEDICADA PARA FAZER ALGUNS INFORMATIVOS SOBRE A FERRAMENTA ")
    print(f"                        NO GERAL E EXPLICAR UM POUCO O INTÚITO DE CADA MÓDULO!\n")
    print(f"╚═══════════════════════════════════════════════════════════════════════════════════════════════════════╝\n")
    print("")
    print(f"{L}1{C} - {B}CONSULTA DE CPF{C}:\n")
    print(f"A consulta de CPF oferece mais de {L}180 milhões de dados {C}a serem consultados!\n{L}Não se assuste caso não encontre o CPF que você deseja,{C} pois às vezes, pode\nestar entre esse restante não presente na ferramenta e em nossos bancos de dados!")
    print(f"")
    print(f"{L}═════════════════════════════════════════════════════════════════════════════════════════════════════════")
    print(f"")
    print(f"{L}2{C} - {B}CONSULTA DE NOME{C}:\n")
    print(f"A consulta de nome possui {L}mais de 224 milhões de dados disponíveis para consulta, {C}ou seja,\nos dados de toda a população brasileira estão presentes em nossos bancos, incluindo algumas\npessoas falecidas. {L}Certifique-se de estar digitando o nome completo{C} para que tenha êxito na consulta e\npossa achar a pessoa desejada... Fazendo isso, é praticamente impossível não achar a respectiva pessoa.")
    print(f"")
    print(f"{L}═════════════════════════════════════════════════════════════════════════════════════════════════════════")
    print(f"")
    print(f"{L}3{C} - {B}CONSULTA PELO NOME DO PAI{C}:\n")
    print(f"A consulta pelo nome do pai simplesmente possibilita encontrar os filhos pelo nome do pai! {L}As vezes\nalgum dos filhos podem não aparecer, então tenha a ciência de que não é 100% garantido encontrar.\n{C}Geralmente funciona melhor com pessoas mais velhas!")
    print(f"")
    print(f"{L}═════════════════════════════════════════════════════════════════════════════════════════════════════════")
    print(f"")
    print(f"{L}4{C} - {B}CONSULTA PELO NOME DA MÃE{C}:\n")
    print(f"{L}Geralmente, a consulta pelo nome da mãe tende a funcionar melhor{C} devido à quantidade de sistemas que\nsolicitam a inclusão do nome da mãe, diferentemente do nome do pai, onde nos cadastros não é obrigatório\ndevido à quantidade de pais ausentes que o Brasil possui!")
    print(f"")
    print(f"{L}═════════════════════════════════════════════════════════════════════════════════════════════════════════")
    print(f"")
    print(f"{L}5{C} - {B}CONSULTA POR RG (BETA){C}:\n")
    print(f"{L}A consulta por RG ainda está sendo desenvolvida... {C}Podem funcionar, no entanto, {L}erros aparecerão!\n{L}Aconselho evitarem o uso desse mecanismo de busca, {C}pois será bem difícil encontrar a respectiva pessoa!")
    print(f"")
    print(f"{L}═════════════════════════════════════════════════════════════════════════════════════════════════════════")
    print(f"")
    print(f"{L}6{C} - {B}CONSULTA DE CNS{C}:\n")
    print(f"A consulta de CNS (Cartão Nacional do SUS) funciona normalmente, porém acredito não ser muito relevante\no uso dessa consulta, já que é algo que não é usado frequentemente. Esse consulta é praticamente garantido\nencontrar os dados do titular do CNS. {L}Possui mais de 180 milhões de CNS em nossos bancos!{C}")
    print(f"")
    print(f"{L}═════════════════════════════════════════════════════════════════════════════════════════════════════════")
    print(f"")
    print(f"{L}7{C} - {B}CONSULTA DE MORADORES PELO CEP{C}:\n")
    print(f"A consulta de moradores pelo CEP possibilita encontrar os {L}dados pessoais dos moradores de determinada\nrua, como CPF, nome completo, nome dos pais e algumas outras informações relevantes. {C}Insira apenas o CEP e será\nretornado alguns moradores daquele determinado CEP. {L}OBS: Alguns dados serão mostrados de forma repetida, é normal{C}!\n")
    print(f"")
    print(f"{L}═════════════════════════════════════════════════════════════════════════════════════════════════════════")
    print(f"")
    print(f"{L}8{C} - {B}CONSULTA DE DADOS POR TELEFONE{C}:\n")
    print(f"Possibilita encontrar dados pessoais de determinada pessoa apenas com o número de telefone. O banco de dados\nresponsável pelas consultas de telefone {L}possui mais de 100 milhões de números cadastrados, {C}porém nem sempre\nserá retornado os dados que você deseja devido as políticas das operadoras cancelarem os chips pré-pagos na auxência\nde recarga e coloca-los para venda novamente. Bem provavel você encontre o respectivo proprietário, {L}porém nem sempre será assim!{C}")
    print(f"")
    print(f"{L}═════════════════════════════════════════════════════════════════════════════════════════════════════════")
    print(f"")
    print(f"{L}9{C} - {B}CONSULTA DE DADOS POR TELEFONE FIXO{C}:")
    print(f"Igual à consulta de telefone mencionada acima, a diferença é que essa consulta serve apenas para telefones fixos.")
    print(f"")
    print(f"{L}═════════════════════════════════════════════════════════════════════════════════════════════════════════")
    print(f"")
    print(f"{L}10{C} - {B}CONSULTA DE DADOS PELO E-MAIL{C}:")
    print(f"{L}Essa é a consulta mais interessante, porém a mais difícil!{C} Essa consulta permite encontrar dados pessoais de\ndeterminada pessoa apenas com o endereço de e-mail do proprietário, no entanto como e-mail é algo relativamente\nmais novo/complexo de se lidar, é mais difícil de retornar os dados! O banco atual de e-mails possui aproximadamente\n{L}10 milhões de e-mails{C} e esse motivo é um dos problemas devido a disparidade de e-mails quando comparado com a população do país.")
    print(f"")
    print(f"{L}═════════════════════════════════════════════════════════════════════════════════════════════════════════")
    print(f"")
    print(f"{L}11{C} - {B}CONSULTA DE CNPJ{C}:")
    print(f"Consulta mais básica, retornado as informações sobre determinado CNPJ, com um único diferencial de mostrar os\nnomes dos respectivos {L}sócios{C} daquela determinada empresa.")
    print(f"")
    print(f"{L}═════════════════════════════════════════════════════════════════════════════════════════════════════════")
    print(f"")
    print(f"{L}11{C} - {B}CONSULTA DE PLACA (OFFLINE){C}:")
    print(f"A consulta de Placa no momento está offline por manutenções, por esse motivo não é possível utilizar o módulo.")
    print(f"")
    print(f"{L}═════════════════════════════════════════════════════════════════════════════════════════════════════════")
    print(f"")
    print(f"{L}13{C} - {B}CHECKER DE OPERADORA{C}:")
    print(f"O checker de operadora permite visualizar de qual operadora/país/estado é determinado número de telefone.\nPode ser verificado o número de todo o planeta {L}desde que seja colocado em formato internacional{C}!\nExemplo de número internacional com um número do Brasil:{L} +5511987654321{C}")
    print(f"")
    print(f"{L}═════════════════════════════════════════════════════════════════════════════════════════════════════════")
    print(f"")
    print(f"{L}14{C} - {B}CONSULTA DE CEP{C}:")
    print(f"A consulta de CEP serve para verificar qual a rua/bairro/município/cidade/estado é o determinado CEP inserido!")
    print(f"")
    print(f"{L}═════════════════════════════════════════════════════════════════════════════════════════════════════════")
    print(f"")
    print(f"{L}15{C} - {B}CONSULTA DE BIN{C}:")
    print(f"A consulta de BIN permite verificar qual o nível e outras informações de um cartão de crédito/débito com os 6 primeiros dígitos do cartão.")
    print(f"")
    print(f"{L}═════════════════════════════════════════════════════════════════════════════════════════════════════════")
    print(f"")
    print(f"{L}16{C} - {B}CONSULTA DE IP/SITE{C}:")
    print(f"Permite verificar de onde é um determinado IP de rede ou site. Essa verificação mostra onde está localizado/hospedador\ndeterminado IP, como cidade, estado, país, provedor, empresa, ASN da iana e outras informações.")
    print(f"")
    print(f"{L}═════════════════════════════════════════════════════════════════════════════════════════════════════════")
    print(f"")
    print(f"{L}16{C} - {B}GERADOR DE PESSOA{C}:")
    print(f"Esse gerador é nada mais que algo para gerar uma pessoa fictícia para algum determinado fim. Geralmente é usado para\npassar sites chatos que pedem cadastro e fazer a verificação dos dados.")
    print(f"{L}NOTA:{C} Os dados gerados são meramente fictícios, então qualquer semelhança é tão/somente coincidência. Nenhum dado gerado aqui é verdadeiro!")
    print(f"")
    print(f"{L}═════════════════════════════════════════════════════════════════════════════════════════════════════════")
    print(f"")
    print(f"{L}16{C} - {B}GERADOR DE CARTÃO DE CRÉDITO{C}:")
    print(f"Os geradores de cartão de crédito servem para diversos fins, um dos mais usados é para passar por sites que exijam\ncadastrar cartão para realizar uma determinada tarefa (Igual aos sites que obrigam adicionar cartão para testar recursos)")
    print(f"{L}NOTA:{C} Os dados gerados são meramente fictícios, então qualquer semelhança é tão/somente coincidência. Nenhum dado gerado aqui é verdadeiro!{C}")
    print(f"")
    print(f"{L}═════════════════════════════════════════════════════════════════════════════════════════════════════════{C}\n\n")
    print(f"")
    print(f"")
    print(f"")
    print(f"                                  ╔══════════════════════════════════════════════════╗\n")
    print(f"                                                   USO DA FERRAMENTA! ")
    print(f"                                              TERMOS E RESPONSABILIDADES\n")
    print(f"                                  ╚══════════════════════════════════════════════════╝\n")
    print(f"")
    print(f"")
    print(f"É DE EXTREMA IMPORTÂNCIA QUE, ANTES DE USAR A FERRAMENTA, O USUÁRIO PRESTE ATENÇÃO E LEIA ATENTAMENTE OS TERMOS E RESPONSABILIDADES DA ABA EM QUESTÃO.")
    print(f"")
    print(f"{L}1.{C} - Termos e responsabilidades")
    print(f"")
    print(f"{L}A.{C} Conformidade com a LGPD e Proteção de Dados - As consultas de dados realizadas pela ferramenta Bad Bitch estão em estrita conformidade com a Lei Geral de Proteção de Dados (LGPD). Isso significa que:\n          - Os dados coletados são utilizados apenas para os fins específicos para os quais foram autorizados.\n          - Os usuários têm o direito de acessar, corrigir ou excluir seus dados pessoais, conforme previsto pela LGPD.\n")
    print(f"{L}B.{C} Uso Indevido das Consultas - O criador da ferrameta não é responsável pelo uso indevido das consultas aqui realizadas. Qualquer uso indevido é estritamente proibido e não reflete a intenção ou responsabilidade do criador.\n")
    print(f"{L}C.{C} Dados Gerados e Coincidências - Dados gerados pela ferramenta que possam coincidir com informações reais são puramente coincidência. O mesmo é projetado para fornecer informações gerais baseadas em dados disponíveis\npublicamente e não garante a precisão ou exatidão das informações fornecidas.\n")
    print(f"{L}D.{C} Uso Consciente e Ético da Ferramenta - Os usuários são incentivados a usar essa ferramenta de maneira consciente e ética. Isso inclui:\n           - Não utilizar a ferramenta para atividades ilegais ou ilícitas.\n           - Respeitar os direitos de privacidade de terceiros.\n           - Não realizar consultas em larga escala que possam sobrecarregar os sistemas ou violar os termos de serviço de terceiros.\n")
    print(f"{L}E.{C} Consequências do Uso Indevido - Qualquer uso indevido do mesmo resultará em medidas disciplinares, incluindo, mas não limitado a, desabilitação dos mecanismos de busca e revogação do acesso à ferramenta.")
    print(f"")
    print(f"")
    print(f"")



R = "\033[0;91m"
B = "\033[1;36m"
C = "\033[1;37m"
Y = "\033[1;33m"
G = "\033[1;32m"
L = "\033[1;35m"
P = "\033[30m"
RT = "\033[40m"
I = '\033[3m'
RESET = '\033[0m'